[build]
  base = "frontend"
  publish = "dist/frontend/browser"
  command = "npm run build:client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
